# Generated by Django 4.1.5 on 2023-01-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(blank=True, choices=[('1', 'Cedula Ciudadana'), ('2', 'Pasaporte'), ('3', 'Cedula Extrangera')], max_length=50, null=True, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento:')),
                ('nombreCompleto', models.TextField()),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesores',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.PROTECT, related_name='curso_docente', to='Academico.profesor'),
            preserve_default=False,
        ),
    ]
